server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  redis:
    cluster:
      nodes: 10.9.216.1:7000,10.9.216.1:7001,10.9.216.1:7002,10.9.216.1:7003,10.9.216.1:7004,10.9.216.1:7005,10.9.216.1:7006,10.9.216.1:7007,10.9.216.1:7008
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
    name: pay
    url: jdbc:mysql://127.0.0.1:3306/order
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logSlowSql: true

tm:
  manager:
    url: http://127.0.0.1:8899/tx/manager/