server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: member
  activemq:
    broker-url: tcp://10.9.216.1:61616
    in-memory: true
    pool:
      enabled: false
  #redis连接信息
  redis:
#    host: 10.9.216.1
#    port: 6379
    cluster:
      nodes: 10.9.216.1:7000,10.9.216.1:7001,10.9.216.1:7002,10.9.216.1:7003,10.9.216.1:7004,10.9.216.1:7005,10.9.216.1:7006,10.9.216.1:7007,10.9.216.1:7008
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
    name: member
    url: jdbc:mysql://127.0.0.1:3306/member
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logSlowSql: true
rocketmq:
  name-server: 10.9.216.1:9876;10.9.217.3:9876
  producer:
    # 发送端发送失败重试的次数，默认两次，可能会带来消息重复发送
    retryTimesWhenSendFailed: 2
    # 发送端需要提供这个，消费端根据topic和group去消费，集群模式，同一个group只会被消费一次
    group: member-group
    # 异步发送模式，同上
    retryTimesWhenSendAsyncFailed: 2
    #发送消息超时时间，单位毫秒，默认 3000（3秒钟）
    sendMessageTimeout: 5000
    # 消息大小超过 4k，则被压缩，默认大小4k
    compressMessageBodyThreshold: 4096
    # 最大消息允许4M
    maxMessageSize: 4194304
    # 消息存储失败，是否允许发送换broker
    retryNextServer: false
##队列
messages:
  queue: messages_queue