server:
  port: 8763
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://10.9.216.1:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    port: 465
    username: lp960419@163.com
    password: lp960419    #授权码
    default-encoding: utf-8
    properties:
      mail.debug: false
      mail.smtp.auth: true   #安全认证(默认是true)
      mail.smtp.ssl.enable: true  #开启ssl加密 否则项目启动时报530error
      mail.smtp.ssl.socketFactory: javax.net.ssl.SSLSocketFactory
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
########################################
msg:
  subject: 李鹏提醒您，会员注册成功邮件。
  text:  恭喜您的账户{},注册成功!

rocketmq:
  name-server: 10.9.216.1:9876;10.9.217.3:9876
  consumer:
    group: member-group
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1
##队列
messages:
  queue: messages_queue